### ISSUE TITLE
Is Octave supported?

### ISSUE THREAD

**Issue by johnnyontheweb** [georgebaltz/SDOF-OSEES#1]
When trying to run code from GNU Octave I get:

`warning: function C:\Users\Giovanni\Desktop\modelliGEN\DYANAS\bundle_postIDA\quantile.m
shadows a core library function
warning: called from
    main_GUI at line 55 column 1
error: 'gui_mainfcn' undefined near line 74 column 5
error: called from
    main_GUI at line 74 column 5`

Will be supported in the future? or Matlab will remain the choice?
thanks and congrats for this interesting work!

**Comment by georgebaltz** [comment]
The GUI functions were developed using MATLAB version 2015; they will work with newer versions but there are problems with older ones, due to MATHWORKs revamping the GUIDE module in the meantime.
One solution would be to compile with a V2015 matlab compiler and then use the executable with the corresponding MRC.
Not sure if all of the post-processing and analysis running functions are octave compatible (which is a priority before starting to talk about making an Octave-compatible GUI).

**Comment by georgebaltz** [comment]
Update: We have developed a standalone version, which does not require a commercial version of matlab to run (just the free-to-download runtime compiler).

http://wpage.unina.it/georgios.baltzopoulos/software/software_page.html
